spring.application.name=ChickenDeliveryBack

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bskmaaekysfmbpwextpc
spring.datasource.password=jHC5NZkncIY2OWAg

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect